# Generated by Django 2.2.7 on 2020-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_tmp',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
