# Generated by Django 2.2.7 on 2020-02-10 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bi.Board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
