# Generated by Django 2.2.7 on 2020-02-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0002_auto_20200209_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Tablero'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario'},
        ),
        migrations.AlterModelOptions(
            name='graph',
            options={'verbose_name': 'Gráfico'},
        ),
        migrations.AlterModelOptions(
            name='typeboard',
            options={'verbose_name': 'Tipos de Tablero'},
        ),
        migrations.AlterModelOptions(
            name='values',
            options={'verbose_name': 'Valores del gráfico'},
        ),
    ]
